title: Default

fields:

  text:
    label: Text
    type:  textarea

files:
    type:
        - image
        - video
        
files:
    width: 800
    height: 600
    
files:
  fields:
    caption:
      label: Caption
      type: textarea
      
      

    
