title: Project

files:
  sortable: true

pages: false

fields:

  title:
    label: Title
    type:  text
    width: 3/4

  type:
    label: Type
    type:  text
    width: 1/4

  text:
    label: Text
    type:  textarea

  street:
    label: URL
    type: text
    
  category:
    label: link text
    type: text

